CREATE TABLE leave_requests
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_name VARCHAR(255) NOT NULL,
    start_date    DATE         NOT NULL,
    end_date      DATE,
    approved      BOOLEAN      NOT NULL
);
